create database photospheredb;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    lastLogin DATETIME NULL,bio VARCHAR(600),
    profilePicture VARCHAR(600),
    uploadCount INT DEFAULT 0,
    subscriptionStart DATETIME NULL,
    subscriptionEnd DATETIME NULL,
    level VARCHAR(100),
    isSuper BOOLEAN DEFAULT NULL
    );

CREATE TABLE albums (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,public BOOLEAN DEFAULT TRUE,cover VARCHAR(600),photoCount INT DEFAULT 0,updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,publisherId INT NOT NULL,FOREIGN KEY (publisherId) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE photos (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255),description TEXT,imageLink VARCHAR(600) NOT NULL,fileSize INT,dimensions VARCHAR(50),state VARCHAR(50),viewCount INT DEFAULT 0,publishedAt DATETIME NULL,createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,userId INT NOT NULL,albumId INT NULL,FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (albumId) REFERENCES albums(id) ON DELETE SET NULL);

CREATE TABLE comments (id INT AUTO_INCREMENT PRIMARY KEY,content TEXT NOT NULL,isArchive BOOLEAN DEFAULT FALSE,createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,userId INT NOT NULL,photoId INT NOT NULL,FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (photoId) REFERENCES photos(id) ON DELETE CASCADE);

CREATE TABLE likes (userId INT NOT NULL,photoId INT NOT NULL,createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (userId, photoId),FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (photoId) REFERENCES photos(id) ON DELETE CASCADE);

CREATE TABLE tags (id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(100) NOT NULL UNIQUE,photoCount INT DEFAULT 0);